include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    unused_element: ignore

linter:
  rules:
    - always_use_package_imports
    - directives_ordering
    - omit_local_variable_types
    - prefer_const_constructors
    - unnecessary_const

